openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/cohort/:
    get:
      operationId: api_cohort_list
      parameters:
      - in: query
        name: degree
        description: A degree code e.g. COMBUS, COMSCI, DS
        schema:
          type: string
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cohort'
          description: ''
    post:
      operationId: api_cohort_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cohort'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Cohort'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Cohort'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cohort'
          description: ''
  /api/cohort/{id}/:
    get:
      operationId: api_cohort_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: A unique value identifying this cohort.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cohort'
          description: ''
    put:
      operationId: api_cohort_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: A unique value identifying this cohort.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cohort'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Cohort'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Cohort'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cohort'
          description: ''
    patch:
      operationId: api_cohort_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: A unique value identifying this cohort.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCohort'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCohort'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCohort'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cohort'
          description: ''
    delete:
      operationId: api_cohort_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: A unique value identifying this cohort.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/degree/:
    get:
      operationId: api_degree_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Degree'
          description: ''
    post:
      operationId: api_degree_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Degree'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Degree'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Degree'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Degree'
          description: ''
  /api/degree/{shortcode}/:
    get:
      operationId: api_degree_retrieve
      parameters:
      - in: path
        name: shortcode
        schema:
          type: string
        description: A unique value identifying this degree.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Degree'
          description: ''
    put:
      operationId: api_degree_update
      parameters:
      - in: path
        name: shortcode
        schema:
          type: string
        description: A unique value identifying this degree.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Degree'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Degree'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Degree'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Degree'
          description: ''
    patch:
      operationId: api_degree_partial_update
      parameters:
      - in: path
        name: shortcode
        schema:
          type: string
        description: A unique value identifying this degree.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedDegree'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedDegree'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedDegree'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Degree'
          description: ''
    delete:
      operationId: api_degree_destroy
      parameters:
      - in: path
        name: shortcode
        schema:
          type: string
        description: A unique value identifying this degree.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/module/:
    get:
      operationId: api_module_list
      parameters:
      - in: query
        name: delivered_to
        schema:
          type: array
          items:
            type: string
        explode: true
        style: form
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Module'
          description: ''
    post:
      operationId: api_module_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Module'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Module'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Module'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Module'
          description: ''
  /api/module/{code}/:
    get:
      operationId: api_module_retrieve
      parameters:
      - in: path
        name: code
        schema:
          type: string
        description: A unique value identifying this module.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Module'
          description: ''
    put:
      operationId: api_module_update
      parameters:
      - in: path
        name: code
        schema:
          type: string
        description: A unique value identifying this module.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Module'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Module'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Module'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Module'
          description: ''
    patch:
      operationId: api_module_partial_update
      parameters:
      - in: path
        name: code
        schema:
          type: string
        description: A unique value identifying this module.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedModule'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedModule'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedModule'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Module'
          description: ''
    delete:
      operationId: api_module_destroy
      parameters:
      - in: path
        name: code
        schema:
          type: string
        description: A unique value identifying this module.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/student/:
    get:
      operationId: api_student_list
      parameters:
      - in: query
        name: cohort
        schema:
          type: string
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
          description: ''
    post:
      operationId: api_student_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Student'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
  /api/student/{student_id}/:
    get:
      operationId: api_student_retrieve
      parameters:
      - in: path
        name: student_id
        schema:
          type: string
        description: A unique value identifying this student.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
    put:
      operationId: api_student_update
      parameters:
      - in: path
        name: student_id
        schema:
          type: string
        description: A unique value identifying this student.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Student'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
    patch:
      operationId: api_student_partial_update
      parameters:
      - in: path
        name: student_id
        schema:
          type: string
        description: A unique value identifying this student.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedStudent'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedStudent'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedStudent'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
    delete:
      operationId: api_student_destroy
      parameters:
      - in: path
        name: student_id
        schema:
          type: string
        description: A unique value identifying this student.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Cohort:
      type: object
      properties:
        id:
          type: string
          maxLength: 50
        year:
          type: integer
          maximum: 4
          minimum: 1
        degree:
          type: string
          format: uri
        name:
          type: string
          readOnly: true
      required:
      - degree
      - id
      - name
    Degree:
      type: object
      properties:
        full_name:
          type: string
        shortcode:
          type: string
          maxLength: 5
      required:
      - full_name
      - shortcode
    Module:
      type: object
      properties:
        code:
          type: string
          maxLength: 5
        full_name:
          type: string
        delivered_to:
          type: array
          items:
            type: string
            format: uri
        ca_split:
          type: integer
      required:
      - code
      - delivered_to
      - full_name
    PatchedCohort:
      type: object
      properties:
        id:
          type: string
          maxLength: 50
        year:
          type: integer
          maximum: 4
          minimum: 1
        degree:
          type: string
          format: uri
        name:
          type: string
          readOnly: true
    PatchedDegree:
      type: object
      properties:
        full_name:
          type: string
        shortcode:
          type: string
          maxLength: 5
    PatchedModule:
      type: object
      properties:
        code:
          type: string
          maxLength: 5
        full_name:
          type: string
        delivered_to:
          type: array
          items:
            type: string
            format: uri
        ca_split:
          type: integer
    PatchedStudent:
      type: object
      properties:
        student_id:
          type: string
          maxLength: 8
        first_name:
          type: string
        last_name:
          type: string
        cohort:
          type: string
          format: uri
        email:
          type: string
          readOnly: true
    Student:
      type: object
      properties:
        student_id:
          type: string
          maxLength: 8
        first_name:
          type: string
        last_name:
          type: string
        cohort:
          type: string
          format: uri
        email:
          type: string
          readOnly: true
      required:
      - cohort
      - email
      - first_name
      - last_name
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
