# Generated by Django 4.1 on 2023-03-28 16:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import university.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('full_name', models.TextField()),
                ('shortcode', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(default=university.models.student_id_generator, max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.cohort')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.TextField()),
                ('ca_split', models.IntegerField(default=0)),
                ('delivered_to', models.ManyToManyField(to='university.cohort')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ca_mark', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('exam_mark', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_cohort', to='university.cohort')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_module', to='university.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_student', to='university.student')),
            ],
        ),
        migrations.AddField(
            model_name='cohort',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.degree'),
        ),
    ]
